language: nix
script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf || true
- sudo pkill nix-daemon || true
- cachix use mafo
- nix-build -o result-wsjtx-udp --argstr compiler $COMPILER default.nix
- nix-build -o result-wsjtx-udp-static default-static.nix
after_success:
- cachix push mafo ./result-wsjtx-udp
- cachix push mafo ./result-wsjtx-udp-static
matrix:
  include:
  - name: GHC 863
    env: COMPILER="ghc863"
