language: nix
script:
- nix-env -iA cachix -f https://cachix.org/api/v1/install
- echo "trusted-users = root ${USER}" | sudo tee -a /etc/nix/nix.conf || true
- sudo pkill nix-daemon || true
- cachix use mafo
- nix-build -o result-wsjtx-udp --argstr compiler $COMPILER default.nix
- nix-build -o result-wsjtx-udp-static default-static.nix
- cp result-wsjtx-udp-static/bin/wsjtx-dump-udp wsjtx-dump-udp_linux-x64-static
after_success:
- cachix push mafo ./result-wsjtx-udp
- cachix push mafo ./result-wsjtx-udp-static
matrix:
  include:
  - name: GHC 865
    env: COMPILER="ghc865"

notifications:
  email:
    recipients:
      secure: "DZKp2uKxT2/807752ZknAlaHFUwb5QzthDjhCd9WTKptujZGTn2kBNr48dgKvTXD4IU4Agyd9yF1acxe2/w/0yrBeLXWZTFP2al0wr17o0zCQRVbRvT/EpROjmxX/BSWnAI3FNgOnczVSotbcMsAUjBRjteu68WDfDuxGVnR06OgSS14UKMwQLnyFYlic5EiMVXcani28RPp1+oDapI8pmoDHYzITH5plGYxa/SNMll3xDLjFRKoZAKTxkoDZiArPElk7LaRFTe0lGN16tQlg7hHCI976osKBjSzRI1xvAz/gYWnHOFRicons/a1F/UDHJYHLZHn992j7OMs9eb5NvxEPfddT7TR49HzuGU2i4Ls2ePUI5p93CfFzsW8Qn4PcPUM/pxdHZzqZsQBjKqdjM8cjsLVPe9umPcJD4lcgY6sTwoz9+2IDiXvHBRthDu5rkBY1brU65t40Z41YUTIJ0ihO0AQ7GrUEjhc5A0iWgoH++v1ch6GBgM8OuNx6nEZ6U3j8QM3blE2HFK24H6OuoldD1ACL40bch03icJyWCnbQ2uhG14BAI4cQ/61J/QbxxZkZhPdvyjylKmjMDEuyl3F2pkZAq0GVk2/TpNxWG8KGic2jASHp8tsphzJtFDIwMWU4pZ+0h/+Ssuglid7s03tJ7xWGE1D1BB8pEGkh3A="
    on_success: change
    on_failure: always

deploy:
  - provider: releases
    api_key:
      secure: Afa47+xKCVR5wdcNSTT3Z3f2vTkuhL/FBVu6rAdj+0Os1r8f9WXY/V2bxMXOf7QfBOOKZZV0VaXo9Zzjtbd4LkxFPSqtZcAxamRj2zlBr7Drb55s0irDwtC7WtafrJSLv8E3+aXjCCBJylF5IqpJAkqnYteHCaONGzKXYacxHDT9nQxF0xHFHLrxT+V6dke1Bq8Q+LxtZmvAMdr68lUxxwMcqxAQKZEnqPfDEswrtPcmsm5/0WqnC954bXaP29I3OW8QmOCgTDqdhuPIPL5sioSNaR2uRtcO+kxeeOgjc30wcb56tcF/iHpuzeOGMY/PQCkSoGHlMAfBswoMsgdjmBARVO1e83oU8aAQ7h8cGoBzywlF4uFBoEZ4LqD3CDvjQYtvzM78/wYjv6MUxSrUHO215xjOl+kizH892KieD1eDu7cGuL/gbVsfz02e/Iw52ncnYMLRn0K0TUvFBqKRfESxB+9+6NGJHwPAMV5ibk3O9CCYg1To/DBuuOaV91YFXfgxgfm3mluqMvGYZeTMAIwxenXNwaITswDXdxXZxn3QZJejJdgvbyTmriypMb+krVQrJrRnyN13OPD5wJyjKRn4tPhxH00BfS+e8vyUU2bu+KqNtCtGKJTBohm/GSeAHgx8rMAkEe+Tr8CXHK8gDzAosPWKMTtswCkEQxphe8o=
    file_glob: true
    file: wsjtx-dump-udp_linux-x64-static
    skip_cleanup: true
    on:
      tags: true
